
spring:
    datasource:
        url: 
        username: 
        password: 
        driver-class-name:
    jpa:
        generate-ddl: 
        show-sql: 
        hibernate:
            ddl-auto: validate
    flyway:
        baseline-on-migrate: 
        user: 
        password: 
        url: 
        schemas:

jwt:
    jwtSecret: 
    jwtExpirationMs: 

server:
    port: 


